name: Deploy React Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push frontend Docker image
      run: |
        docker build -t myusername/frontend ./frontend
        docker push myusername/frontend
